[pytest]
# 命令行参数
addopts = -vs  --alluredir=./temps --clean-alluredir

#-v 详细输出结果
#-s 允许打印
#--alluredir=./temps 指定 Allure 报告生成的临时目录为./temps
#--clean-alluredir 每次运行前先清空./temps目录

disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
#保留中文和字符串正常显示，不转义


#日志配置
#日志文件的配置
log_file = ./logs/frame.log

#日志的级别（DEBUG调试，INFO信息，WARNING警告，ERRO错误，CRITICAL非常严重）
log_file_level = info

#日志格式，级别|时间戳|内容
log_file_format = %(levelname)s|%(asctime)s|%(message)s